variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  only:
    changes:
        - src/**/*
        - public/**/*

  image: node:16.15.0
  artifacts:
    paths:
      - public
  script:
    - yarn
    - yarn build
  tags:
    - deploy
